<a href="https://colab.research.google.com/github/AkshatNGupta/Introduction-to-Machine-Learning/blob/master/Iris_knn_nearest_neighbor's.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the libraries i need for this project

In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

We add the dataset iris data set which is present in scikit learn datasets module and then load it.

In [ ]:
iris_dataset=load_iris()

Now we display the object returned to us to know what are its labels and other details

In [ ]:
print("Keys of iris_dataset:\n{}".format(iris_dataset.keys()))

Keys of iris_dataset:
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


Now we display the description of the data set that we have using he ey DESCR

In [ ]:
print(iris_dataset['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

Lets now print the categories of values we expect to classify our flowers into, which is present in target names

In [ ]:
print("Target Names:{}".format(iris_dataset['target_names']))

Target Names:['setosa' 'versicolor' 'virginica']


Now we print the parameters on which we want to predict the type of flower which is present in feature names

In [ ]:
print("Feature names:{}".format(iris_dataset['feature_names']))

Feature names:['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Lets see what is the file name. Just checking out of curiosity lol😂 

In [ ]:
print("file name:{}",iris_dataset['filename'])

file name:{} /usr/local/lib/python3.6/dist-packages/sklearn/datasets/data/iris.csv


Now we see the type of dat present in data sets

In [ ]:
print("Type of data: {}".format(type(iris_dataset['data'])))

Type of data: <class 'numpy.ndarray'>


Now we take the shape of the data array to know about its rows and columns

In [ ]:
print("Shape of the data: {}".format(iris_dataset['data'].shape))

Shape of the data: (150, 4)


Now we print the first five datas just for information

In [ ]:
print("First five columns of data:\n {}".format(iris_dataset['data'][:5]))

First five columns of data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


Now we see the type of array of the target

In [ ]:
print("Type of the target: {}".format(type(iris_dataset['target'])))

Type of the target: <class 'numpy.ndarray'>


Now as you might have guessed we also print its shape just to know its rows and columns

In [ ]:
print("Shape of the target: {}".format(iris_dataset['target'].shape))

Shape of the target: (150,)


Following the trend we print top 5 or all the values in target

In [ ]:
print("Target:\n{}".format(iris_dataset['target']))

Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


0=setosa 1=versicolor' 2=virginica

Now our actual project begins. We create a tariing data set and test dataset from the pre data set which will split he original data set in the ratio of 75:25 and then we rearrange it so that it takes random values to train and test the model

In [ ]:
X_train ,X_test ,y_train ,y_test=train_test_split(iris_dataset['data'],iris_dataset['target'],random_state=0)

Since we already knw the type so now we just go for shape and print the shape of our new test and training datasets. why is x train y test only used i did not get, I'll do research later 

In [ ]:
print("X_train shape:{}".format(X_train.shape))
print("y_train shape:{}".format(y_train.shape))
print("X_test shape:{}".format(X_test.shape))
print("y_test shape:{}".format(y_test.shape))

X_train shape:(112, 4)
y_train shape:(112,)
X_test shape:(38, 4)
y_test shape:(38,)


Now we use the method of k nearest neighbours to predict what is the type of that flower based on the lengths entered. Here we can take the value of k as we wish from 1 to total no of data points for better results

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)

Since we have now created the bot now we train it using the fit method

In [ ]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

Now we create a new data poimnt and give it to our newly trained bot and give that random data to see what values it predicts, but before that we again show its shape as usual...ughhhh

In [ ]:
X_new=np.array([[6,3.5,4.2,1.3]])
print("X_new.shape:{}".format(X_new.shape))

X_new.shape:(1, 4)


Finally bot will predict the output. Background voices silent, final hour of test..........we give the data to the bot stored in X_new

In [ ]:
prediction=knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Predicted target name:{}".format(iris_dataset['target_names'][prediction]))

Prediction: [1]
Predicted target name:['versicolor']


Now we evaluate the mdel based on the test data we seerated from the main data set

In [ ]:
y_pred=knn.predict(X_test)
print("Test set preictions:\n{}".format(y_pred))

Test set preictions:
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


Now we check how it has performed in terms of score:

In [ ]:
print("Test set score: {}".format(np.mean(y_pred==y_test)))

Test set score: 0.9736842105263158


THANKYOU FOR STAYING CONNECTED!